### ISSUE TITLE
make zkbtc CLI check if it is up-to-date

### ISSUE THREAD

**Issue by mimoo** [sigma0-xyz/zkbitcoin#11]
not sure how we can do that, but since we're changing a lot of things these days, better make sure that the CLI understands that it is out of date (if it is)

**Comment by xJonathanLEI** [comment]
Step one would be to make releases to GitHub I guess. Shameless plug but can take a look at [how Starkli does releases](https://github.com/xJonathanLEI/starkli/blob/master/.github/workflows/release.yml).

**Comment by mimoo** [comment]
we accept PRs :D

**Comment by xJonathanLEI** [comment]
Yeah just sent my first one: #17.
