### ISSUE TITLE
limit memory growth of a node

### ISSUE THREAD

**Issue by mimoo** [sigma0-xyz/zkbitcoin#2]
A node keeps track of signing tasks locally:

```rust
signing_tasks: RwLock<HashMap<Txid, LocalSigningTask>>
```

they might grow that hashmap infinitely if they don't perform the second round of a `LocalSigningTask`, which is created during round 1 but only deleted at the end of a round 2.

Thus, we should limit that growth. Naive solution is to also keep track of a queue `last_tasks: Vec<Txid>` that is limited in size (maybe 100?), and when we reach its capacity then pop the oldest inserted element and remove it from the `signing_tasks` as well. We should also log the fact that we reached the capacity. A sure way of not blocking the network is to have a log when we reach half the capacity, a quarter of the capacity, etc.

**Comment by mimoo** [comment]
from @imikushin which is also a good idea: 

> perhaps notify nodes to abort generating their signature share if we don't need them anymore

**Comment by ppoliani** [comment]
@mimoo the idea of having a `last_tasks` vector is pretty simple and easy to understand. We could also wrap this logic inside a custom generic structure e.g. `CappedHashMap`. 

I can look into this if no one else is working on it.

**Comment by ppoliani** [comment]
Regarding this comment
> perhaps notify nodes to abort generating their signature share if we don't need them anymore

I believe this should be part of a separate PR. The current WIP [implementation](https://github.com/sigma0-xyz/zkbitcoin/pull/25/files#diff-99a73d8c456a3d79be4ff24492477127601c120f1eaffcdd00f7dbd914cb5754R29) of the `CappedHashMap` will return `Some(key)` when inserting a new task. `key` is the key that is removed when the collection reaches full capacity.

So whoever calls this function can check if a key was removed and then notify the other nodes about this.
