### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by ppoliani** [sigma0-xyz/zkbitcoin#41]
Before we can merge this https://github.com/sigma0-xyz/zkbitcoin/pull/33#issue-2117112857 we would need to create at least release. 

> The tag of the release commit should start with `v` e.g. `v0.1.0`

**Comment by mimoo** [comment]
cc @imikushin

**Comment by imikushin** [comment]
We have our first release: https://github.com/sigma0-xyz/zkbitcoin/releases/tag/v0.1.0
