### ISSUE TITLE
add sanction list of UTXO/bitcoin address to remain compliant

### ISSUE THREAD

**Issue by mimoo** [sigma0-xyz/zkbitcoin#5]
I think there are some OFAC lists somewhere of addresses or UTXO we're not supposed to interact with, we should make sure we don't ever go to production without taking that into account

**Comment by ppoliani** [comment]
There a tool that we can look into to take some ideas https://github.com/0xB10C/ofac-sanctioned-digital-currency-addresses.

It extracts sanctioned addresses from this official repository https://ofac.treasury.gov/specially-designated-nationals-and-blocked-persons-list-sdn-human-readable-lists

**Comment by mimoo** [comment]
that would be awesome!

**Comment by ppoliani** [comment]
@mimoo I think we can close this issue.
